*** Variables ***
${BASE_URL}              http://localhost:3000
${URL_LOGIN}             http://localhost:3000/login
${URL_REGISTER}          http://localhost:3000/register
${URL_SEARCH}            http://localhost:3000/search
${URL_APPOINTMENTS}      http://localhost:3000/appointments
${BROWSER}         chrome

${PATIENT_EMAIL}         adresse.test@email.com
${PATIENT_PASSWORD}      Password123#

${PRACTITIONER_EMAIL}       dr.martin@medibook.fr
${PRACTITIONER_PASSWORD}    Praticien123!

